server:
  port: 8080

spring:
    application.name: gateway
    cloud:
      gateway:
        default-filters:
        - PrefixPath=/
        routes:
        - id: user
          uri: lb://user
          predicates:
          - Path=/user/**
          filters:
          - StripPrefix=1
        - id: visualization-tool
          uri: lb://visualization-tool
          predicates:
          - Path=/visualization-tool/**
          filters:
          - StripPrefix=1